// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// HandlerItf is an autogenerated mock type for the HandlerItf type
type HandlerItf struct {
	mock.Mock
}

// CollectSymbol provides a mock function with given fields: _a0
func (_m *HandlerItf) CollectSymbol(_a0 *gin.Context) {
	_m.Called(_a0)
}

// DeleteSymbol provides a mock function with given fields: _a0
func (_m *HandlerItf) DeleteSymbol(_a0 *gin.Context) {
	_m.Called(_a0)
}

// GetSymbols provides a mock function with given fields: _a0
func (_m *HandlerItf) GetSymbols(_a0 *gin.Context) {
	_m.Called(_a0)
}

// StoredData provides a mock function with given fields: _a0
func (_m *HandlerItf) StoredData(_a0 *gin.Context) {
	_m.Called(_a0)
}

// NewHandlerItf creates a new instance of HandlerItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerItf {
	mock := &HandlerItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
